#version
version: "3.0"

#services
services:
    angular: 
        build: Onlinetest
        ports: 
          -   "4200:4200"
   
   
    express: 
        build: server 
        ports: 
         -    "8080:8080"
        links: 
         -  mongodb 
    
    
    mongodb: 
        image: mongo
        ports: 
         -     "27017:27017"
    
